<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Legal Helmy</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="icon" href="css/images/favicon.png">
</head>
<!-- <body echo obtenerPaginaActual;// -->
<body class="backLegal">
    <div class="boxLegal">
        <div class="logTaLegal">
            <img src="css/images/logoEdison.png" alt="">
        </div>
        <div class="logHelmyLegal">
            <img src="css/images/LogoHelmy.png" alt="">
        </div>
        <div class="textosLegal">
            <h2>Acepto términos y condiciones, términos y condiciones Marketplace y autorizo el tratamiento de mis datos personales.</h2>
            <h4>TÉRMINOS Y CONDICIONES</h4>
            <p> 
                PÁGINA WEB<br>
                Los siguientes son los términos y condiciones que regulan el acceso y el uso a los contenidos de la página web www.helmy.com, los términos y condiciones son de carácter general y regulan el contenido y uso de la web en su conjunto. No obstante, lo anterior, algún servicio o contenido específico de la web puede requerir para su acceso y uso la aceptación de unos términos y particulares por parte del usuario.
                Se entenderá como usuario, toda persona que acceda, navegue o utilice los contenidos y/o servicios que puedan encontrarse en la web en cada momento. En lo sucesivo, se referirá al usuario de esta web como "Usuario" o "Usuarios". El usuario que además adquiera cualquier producto y/o contrate cualquier servicio ofrecidos a través de la web será denominado "Cliente", siendo estos mayores de 18 años o, en caso de menores, tutelados que actúen bajo la debida supervisión de su tutor o responsable legal. El conjunto de los productos y servicios que se ofrezcan en la web y que pueden ser adquiridos por el usuario serán denominados "Productos".
                El acceso y uso de la web, y en su caso la adquisición de cualquier producto ofrecido en la misma, por parte de un usuario y/o cliente, implica la aceptación por el mismo de la totalidad de los términos y condiciones sin ninguna condición ni reserva.
                El acceso a la web es de carácter libre y gratuito. Sin embargo, el usuario deberá realizar el registro de los datos para acceder a contenidos específicos, el usuario podrá: revisar su perfil previamente registrado en Helmy App, para ello deberá ingresar con el mismo usuario y contraseña allí almacenados. Y en caso de querer realizar una compra desde la web www.helmy.com, esta lo redireccionará al sitio destinado para tal efecto, www.store.helmy.com.co donde deberá realizar el registro de sus datos y posteriormente podrá revisar sus compras y el estado de  las mismas.
                Es obligatorio completar el formulario de registro en todos sus campos con datos válidos para convertirse en usuario autorizado de www.store.helmy.com.co, así mismo podrá acceder a las promociones, y adquirir los productos ofrecidos en este sitio. El futuro usuario TA EDISON S.A.S. deberá completar el formulario de registro con su información personal de manera exacta, precisa y verdadera ("Datos Personales") y asume el compromiso de actualizar los datos personales conforme resulte necesario. TA EDISON S.A.S. podrá utilizar diversos medios para identificar a su usuario , pero TA EDISON S.A.S. NO se responsabiliza por la certeza de los datos personales provistos por sus usuarios. Los usuarios garantizan y responden, en cualquier caso, de la exactitud, veracidad, vigencia y autenticidad de los datos personales ingresados. Cada usuario sólo podrá ser titular de 1 (una) cuenta TA EDISON S.A.S., no pudiendo acceder a más de 1 (una) cuenta TA EDISON S.A.S. con distintas direcciones de correo electrónico o falseando, modificando y/o alterando sus datos personales de cualquier manera posible. Si se verificara o sospechará un uso fraudulento y/o malintencionado y/o contrario a estos términos y condiciones y/o contrarios a la buena fe, TA EDISON S.A.S. tendrá el derecho inapelable de dar por terminados los créditos, dar de baja las cuentas y hasta de perseguir judicialmente a los infractores.
                TA EDISON S.A.S. se reserva el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los datos personales, así como de suspender temporal o definitivamente a aquellos usuarios cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitación, TA EDISON S.A.S. podrá dar de baja la compra efectuada, sin que ello genere derecho alguno a resarcimiento, pago y/o indemnización.
                El usuario, una vez registrado, dispondrá de su dirección de email y una clave secreta e intransferible (en adelante la "Clave") que le permitirá el acceso personalizado, confidencial y seguro. En caso de poseer estos datos, el usuario tendrá la posibilidad de cambiar la clave de acceso, para lo cual deberá sujetarse al procedimiento establecido en el sitio respectivo. El usuario se obliga a mantener la confidencialidad de su clave de acceso, asumiendo totalmente la responsabilidad por el mantenimiento de la confidencialidad de su clave secreta registrada en este sitio web, la cual le permite efectuar compras, solicitar servicios y obtener información (en adelante la "Cuenta"). Dicha clave es de uso personal, y su entrega a terceros no involucra responsabilidad de TA EDISON S.A.S. o de las empresas en caso de utilización indebida, negligente y/o incorrecta.
                El usuario será responsable por todas las operaciones efectuadas en y desde su cuenta, pues el acceso a la misma está restringido al ingreso y uso de una clave secreta, de conocimiento exclusivo del usuario. El usuario se compromete a notificar a TA EDISON S.A.S., en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su cuenta y/o clave, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión, préstamo o transferencia de la clave y/o cuenta bajo ningún título.
                TA EDISON S.A.S., se reserva el derecho de rechazar cualquier solicitud de registro o de cancelar un registro previamente aceptado, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.
                Proceso de compra
                El usuario podrá realizar la compra de los productos Helmy, a través de dos canales:
                1.	Terceros: Helmy cuenta con una red de distribuidores (ver distribuidores) en los cuales el usuario podrá adquirir tanto Helmy-C como el sistema Helmy completo (Helmy-C y Helmy-M) de forma presencial, así mismo identificar el taller más cercano para la instalación de Helmy-M.
                2.	Pagina web www.store.helmy.com, el usuario podrá adquirir únicamente el dispositivo Helmy-C, de la siguiente manera:
                •	REGISTRO: El usuario deberá estar registrado en la plataforma, en caso estarlo ingresará directamente con su usuario y contraseña, de lo contrario deberá diligenciar el formulario para la creación de su cuenta.
                •	PRODUCTO: Seleccione el producto a comprar e indique la cantidad. 
                •	VALIDACIÓN DE COMPRA: el usuario deberá realizar la confirmación del contenido de la orden, verificando los datos de su compra.
                •	PAGO: El pago se realizará por la pasarela de pagos PayU, con diversas opciones como tarjeta débito, crédito, giros etc.
                •	CONFIRMACION DE COMPRA: Una vez realizado el pago, será enviada la confirmación de la compra al correo electrónico registrado previamente
                TA EDISON S.A.S. se ha aliado comercialmente con pasarela de pagos PayU, compañía encargada de proteger a los Usuarios contra el riesgo de robo cuando realizan sus órdenes de compra con tarjetas de crédito. La misión de pasarela de pagos entonces consistirá en verificar que el usuario esté efectivamente en el origen de las órdenes realizadas en su nombre a través de www.store.helmy.com y, por tanto, que su información personal y/o bancaria no han sido usurpadas.
                Como parte de esa revisión, pasarela de pagos podrá eventualmente llegar a realizar una llamada telefónica al usuario para comprobar la veracidad del pago. El vendedor no podrá proceder con el alistamiento de la orden, mientras el usuario no haya sido contactado por parte de pasarela de pagos.
                Al utilizar una tarjeta de crédito o débito, el nombre del titular de dicha tarjeta debe coincidir con el nombre utilizado al registrarse en el portal de TA EDISON S.A.S. De lo contrario, se podría anular la operación. Bajo cualquier sospecha y/o confirmación de compras no autorizadas TA EDISON S.A.S. cancelará la compra, efectuará el reverso a la tarjeta de forma automática y estará facultado para iniciar acciones judiciales en contra de la persona que haya llevado a cabo la transacción sospechosa. Así mismo, TA EDISON S.A.S. podrá en los términos de la ley, entregar la información personal de quien haya realizado la transacción sospechosa a los tarjetahabientes afectados.
                Envíos
                Todos los envíos realizados por TA EDISON S.A.S. están soportados por las mejores compañías de transporte en el territorio Colombiano. El usuario estará sujeto a la política, tiempos de entrega, intentos de entrega, ausencias, comunicación y demás aspectos de xxxxx. (link de la política del aliado)
                Para tener en cuenta:
                •	Es responsabilidad del Usuario brindar todos sus datos de forma completa y correcta, ya que de ello depende el éxito de su entrega. Así mismo al momento de la entrega deberá verificar que las cintas de seguridad no estén alteradas y que el contenido corresponda al solicitado, en caso de detectar alguna anomalía anótelo en la planilla del transportador, firme el comentario y comuníquese con nuestra línea de atención al cliente (1) 9373083, de lo contrario TA Edison S.A.S., no se hará responsable por los daños que puedan presentar los productos.
                •	El valor del envío será cancelado por el usuario desde su compra inicial, por lo cual no deberá realizar ningún pago al momento de la entrega.
                •	Ningún empleado de las empresas de mensajería está autorizado a instalar equipos, retirar accesorios, etc.
                •	La empresa transportadora con el fin de facilitar el seguimiento de los pedidos realizados por los usuarios en la página, podría enviar información vía mensajes de texto (SMS y/o MMS) o vía "WhatsApp" acerca de la entrega y estado de los pedidos realizados en el sitio. Los usuarios no podrán presentar dudas acerca de sus pedidos ni interactuar vía mensajes de texto (SMS y/o MMS) o vía "WhatsApp", este será solo de manera informativa y de seguimiento.
                •	El tiempo de entrega, en días hábiles (lunes a viernes, no festivos) empieza a correr después de la confirmación de la disponibilidad de los productos ordenado. Dichos tiempos están condicionados a la validación del pedido por parte de la pasarela de pagos. Dentro del tiempo de entrega se comprende la entrega de los productos a domicilio, la preparación y envío del pedido. Los tiempos de entrega pueden variar de acuerdo con el destino y pueden ser entregados en cualquier horario del día.
                •	TA EDISON S.A.S. no realizará entregas de compras realizadas en www.store.helmy.com por medio de nuestra tienda web en tiendas fiscas de los distribuidores autorizados.

                Derecho de retracto 
                Conforme al artículo 47 del Estatuto del Consumidor los usuarios podrán ejercer el derecho de retracto del producto adquirido dentro de los (5) cinco días hábiles posteriores a la recepción del bien, siempre y cuando lo permita su naturaleza y el estado del bien y su empaque sea el mismo en el que lo recibió. Las reversiones se harán por el valor del producto pagado por el cliente en la respectiva transacción. En ningún caso TA EDISON S.A.S. hará reversiones parciales del valor de un producto. Cabe aclarar que cada Distribuidor maneja sus propias políticas de retracto, es responsabilidad del Usuario conocer esta información. Ver distribuidores (link)
                Para devolver un producto, el usuario deberá ponerse en contacto con el mismo lugar donde realizo su compra, para las compras realizadas por www.store.helmy.com.co deberá contactarse con TA EDISON S.A.S. y para compras físicas, deberá ponerse en contacto con Distribuidor donde realizó dicha compra.
                La devolución de un producto se hará de conformidad con los términos y condiciones indicados en el Estatuto del Consumidor, y, en lo que no contradiga a éste, por los términos y condiciones especificados por cada vendedor. Todo producto debe ser devuelto en las mismas condiciones en las cuales fue recibido, con todos los accesorios suministrados de ser el caso (auriculares, dispositivos, manuales, empaque, etc.), sin daños, sin ser utilizado y en su embalaje original.
                No se aceptará la devolución para efectos de retracto el producto que no presente los sellos de seguridad, con signos de haber sido usados o manipulados bajo condiciones que se estiman van más allá de las necesarias para verificar sus condiciones de entrega.
                Después de realizar el retracto en página, el cliente tendrá 5 días hábiles para comunicarnos la guía de logística inversa para la devolución de producto, si el producto no es enviado dentro de este plazo, se entenderá que el cliente desea cancelar el retracto.
                Reclamaciones y Garantías
                Cualquier reclamación sobre la no conformidad o la calidad de los Productos deberá ser realizada directamente por el Cliente a través de la línea de atención de TA EDISON S.A.S. en Bogotá al número (1) 9373083
                La garantía de los Productos será de seis (6) meses a partir de la recepción del producto, esta garantía se realizará únicamente por defectos de fabricación y no cubrirá la mala manipulación o instalación inadecuada del producto.<br> 
                APLICACIÓN MOVIL<br> 
                Los siguientes son los términos y condiciones que regulan el acceso y el uso a los contenidos de la plataforma móvil HELMY-APP, los Términos y Condiciones son de carácter general y regulan el contenido y uso de la Aplicación (en adelante “App”) en su conjunto. No obstante, lo anterior, algún servicio o contenido específico de la App puede requerir para su acceso y uso la aceptación de unos términos y particulares por parte del Usuario.
                Se entenderá como usuario, toda persona que acceda, navegue o utilice los contenidos y/o servicios que puedan encontrarse en la App en cada momento. En lo sucesivo, se referirá al usuario de esta App como "Usuario" o "Usuarios", siendo estos mayores de 18 años o, en caso de menores, tutelados que actúen bajo la debida supervisión de su tutor o responsable legal.
                La aplicación funcionará como un canal de conexión bluetooth entre los dispositivos Helmy-C y Helmy-M. El usuario se compromete a leer los términos y condiciones aquí establecidas, previamente a la descarga de la aplicación, por tanto, en caso de realizar la instalación se entiende que cuenta con el conocimiento integral de este documento y la consecuente aceptación de la totalidad de sus estipulaciones.
                En la aplicación se pondrá a disposición del cliente información y/o permitirá la realización de las acciones determinadas o habilitadas por TA EDISON S.A.S. para el sistema Helmy. TA EDISON S.A.S. podrá adicionar, modificar o eliminar las funcionalidades en cualquier momento, lo cual acepta el usuario mediante la instalación de la aplicación. En todo caso, al momento de realizar dichas modificaciones se notificarán al usuario a través de la misma aplicación móvil una vez inicie sesión.
                Requisitos de uso
                El usuario deberá contar con un dispositivo móvil inteligente Smartphone, con sistema operativo Android, la descarga de la aplicación será directamente por la “Play store”. Deberá contar con acceso a internet para realizar el registro de sus datos y la configuración inicial de sus dispositivos, para el inicio de recorridos la aplicación Helmy-App funciona en modo offline. TA EDISON S.A.S., no será responsable por la seguridad de los equipos Smartphone propiedad de los usuarios utilizados para el acceso al canal, ni por la disponibilidad del servicio o el funcionamiento en los dispositivos en los cuales se descargue la aplicación.
                Para acceder al portal, el cliente contará con usuario y clave, que lo identifica en su relación con Helmy-App, los cuales serán los mismos utilizados en el portal web. 
                Registro del usuario en la plataforma 
                Con el fin de acceder a todos los servicios ofrecidos por la App, el usuario deberá completar un registro en el cual se creará un nombre de usuario y contraseña. El nombre de usuario y la contraseña que el usuario proporciona son sus credenciales para acceder al sitio web y/o aplicación móvil. Los usuarios no pueden tener más de un conjunto activo de credenciales. Además, a los usuarios se les prohíbe vender, negociar o ceder de otra manera sus credenciales en La App a otra persona. Si el usuario escoge registrarse, a su vez, acepta los presentes Términos y Condiciones y se compromete a suministrar información actual, completa y verídica sobre él o ella. Toda la información personal suministrada por el usuario en la App, se regirá por las políticas de privacidad de Helmy-App.
                Obligaciones de los Usuarios
                El Usuario se obliga a usar la aplicación y las acciones disponibles en ella de una manera diligente, correcta, lícita y en especial, se compromete a:
                •	Brindar los datos reales y correctos sobre la información personal, los datos de su motocicleta y datos de contacto de emergencia, TA EDISON S.A.S. no será responsable por errores en la digitación o datos incorrectos por parte del usuario.
                •	Mantener de forma permanente saldo para envío de mensajes de texto desde su dispositivo. TA EDISON S.A.S. no será responsable en caso del no envío de alerta por falta de saldo.
                •	Utilizar los contenidos con fines o efectos contrarios a la ley, a la moral y a las buenas costumbres generalmente aceptadas o al orden público.
                •	No reproducir, copiar, representar, utilizar, distribuir, transformar o modificar los contenidos de la aplicación, por cualquier procedimiento o sobre cualquier soporte, total o parcial, o permitir el acceso del público a través de cualquier modalidad de comunicación pública.
                •	No permitir que terceros ajenos a él usuario usen la aplicación móvil con su clave, en tal caso, será bajo la responsabilidad del Usuario, TA EDISON S.A.S. no será responsable por cualquier pérdida o daño que se llegue a presentar a causa de este incumplimiento. 
                Obligaciones de TA EDISON S.A.S.
                •	Garantizar el uso adecuado de los datos recolectados por los usuarios, con los fines dispuestos en nuestra política de tratamiento de datos (link)
                •	Procurar garantizar disponibilidad, continuidad o buen funcionamiento de la aplicación. TA EDISON S.A.S. podrá bloquear, interrumpir o restringir el acceso a esta cuando lo considere necesario para el mejoramiento de la aplicación o por dada de baja de esta. Así mismo, TA EDISON S.A.S., no será responsable por los retrasos, no procesamiento de información o suspensión del servicio del operador móvil.
                •	En caso de que TA EDISON S.A.S., detecte distintas cuentas que contengan datos coincidentes o relacionados, podrá cancelar, suspender o inhabilitarlas, sin que esto genere ningún derecho a favor del usuario de reparación o reembolso de los dineros abonados.
                •	Informar al usuario, en caso de realizar cualquier mejora técnica que permita incorporar un mayor número de prestaciones al servicio.
                •	Dar por terminado cuentas que estén inactivas por un periodo de tiempo extendido.
                •	Prestar el adecuado soporte al Usuario en caso de ser necesario.
                Las presentes condiciones de uso constituyen el acuerdo completo entre el usuario TA EDISON S.A.S., en relación con el acceso a la aplicación móvil, sitio web, portal web y/o uso de la aplicación móvil, sitio web, portal web y/o el servicio. La omisión por parte de TA EDISON S.A.S. en el ejercicio o la exigencia de cumplimiento de cualquier derecho o disposición contenida en las presentes condiciones de uso no constituirá una renuncia a dicho derecho o disposición en ese caso concreto o en cualquier otro.
                Si alguna disposición del presente contrato es declarada inválida, el resto del presente contrato permanecerá vigente en todos sus aspectos. Si cualquier disposición de las presentes condiciones de uso es declarada ilegal, nula o inaplicable por cualquier causa, esa disposición quedará excluida de las presentes condiciones de y sin afectar a la validez y aplicabilidad de las restantes disposiciones.<br> 
        </p>
        <p>
            Política de tratamiento de datos personales<br>
            Introducción<br>
            Su privacidad es importante para TA Edison. Esta declaración de privacidad explica cuáles son los datos personales que recopila TA Edison, cómo los trata y con qué fines lo hace. 
            TA Edison es una compañía líder en Colombia que tiene como actividad principal el diseño, la fabricación, elaboración, desarrollo, distribución, comercialización, importación y exportación de toda clase de productos y servicios asociados a dispositivos electrónicos de consumo masivo, tarjetas impresas, circuitos integrados y productos derivados de ellos. Así mismo, la sociedad desarrollará software especializado, enfocado, pero no limitado a: Aplicaciones móviles, bases de Datos, Servicios con Blockchain, Aplicaciones WEB, Aplicaciones cliente-Servidor, Servicios que hacen uso de Inteligencia Artificial, servicios que hacen uso de Big Data, Cloud Computing, desarrollo de Software a medida, criptografía y seguridad informática. TA Edison cuenta con una plataforma virtual compuesta por una página web y una aplicación móvil, y una red de aliados para la distribución y comercialización de nuestros productos y servicios.
            Consulte los detalles específicos de cada producto de TA Edison, en esta declaración de privacidad.
            Alcance
            Este aviso se aplica a todos los usuarios de los servicios de TA Edison en cualquier parte del mundo, incluidos los que usa aplicación móvil de HELMY, sitios web, dispositivos u otros servicios.
            Recopilación y usos de los datos
            A.	 Datos recopilados
            TA Edison recopila lo siguiente:
            •	Datos proporcionados por usuarios a TA Edison, como los generados durante la creación de cuentas.
            •	Datos creados durante el uso de nuestros productos y servicios, como detalles del dispositivo, y ubicación.
            •	Datos de otras fuentes, como los solicitados por la red de aliados.
            La siguiente información es recopilada por TA Edison:
            1. Datos proporcionados por usuarios. Esto incluye lo siguiente:
            Perfil de usuario: Recopilamos los datos generados cuando los usuarios crean o actualizan credenciales de sus cuentas asociadas con nuestro productos y servicios. La información puede incluir su nombre, correo electrónico, número de teléfono, nombre de usuario y contraseña, dirección, foto de perfil, detalles de pago o bancarios (incluido su chequeo), documentos de identificación gubernamentales, números e imágenes de la licencia de conducir, fecha de nacimiento, grupo sanguíneo, firma y foto. También se incluye la información de vehículos o de seguros motocicletas, seguros de salud, administradoras de riesgos laborales, y los ajustes del usuario. 
            En el caso de la aplicación móvil HELMY, recopilamos datos de un contacto, que puede incluir, nombre, número de teléfono, dirección y otros, con el fin de enviarle un mensaje vía SMS en caso de que la aplicación móvil detecte un accidente.
            2. Datos creados durante el uso de nuestros servicios o productos. Esto incluye lo siguiente:
            Datos de ubicación: Si el usuario lo permite, recopilamos datos de ubicación precisos o aproximados de su dispositivo móvil. Recopilamos datos en el caso en que la aplicación móvil HELMY se ejecute en primer plano (abierta y en pantalla) o en segundo plano (abierta, pero no en pantalla) de su dispositivo móvil. Los usuarios pueden usar la aplicación móvil HELMY sin permitir que se recopilen datos de ubicación de sus dispositivos móviles. Sin embargo, esto puede afectar la disponibilidad de algunas funciones. Por ejemplo, si un usuario apaga su GPS no permitirá que se recopilen datos de ubicación, y en caso de accidente no podrá enviarse el mensaje SMS al contacto de emergencia con la ubicación real. 
            Información de transacciones: Recopilamos datos de las transacciones relacionadas con el uso de nuestros servicios, lo que incluye el tipo de servicio solicitado o prestado, fecha y hora de citas agendadas con nosotros o nuestros aliados. También, recopilamos información de transacciones de compra de nuestros productos, que es utilizada para el envío de productos a domicilio, esto incluye los datos del destinatario y del remitente. 
            Datos de uso: Recopilamos información sobre cómo los usuarios interactúan con nuestros servicios, como la fecha y la hora de acceso, funciones de la aplicación móvil HELMY páginas visitadas, fallos de la aplicación móvil HELMY y otras actividades del sistema, tipo de navegador, y sitios o servicios de terceros usados antes de interactuar con nuestros servicios. En algunos casos recopilamos estos datos a través de cookies, píxeles, etiquetas y tecnologías similares que crean y mantienen identificadores exclusivos. También, recopilamos fecha y hora de eventos detectados por nuestros productos (accidente en motocicleta, robo de motocicleta, entre otros).
            Datos del dispositivo: Podemos recopilar datos sobre los dispositivos usados para acceder a nuestros servicios, lo que incluye modelos de hardware, dirección IP, sistemas operativos y versiones, software, idiomas preferidos, identificadores únicos del dispositivo, identificadores de publicidad, números de serie, e información de movimiento del dispositivo o de las redes móviles.
            Contenido del usuario: En cuanto a la aplicación móvil HELMY, recopilamos la información de la conducta de manejo de los conductores como velocidad, uso correcto de casco entre otros, periodos de tiempo que usa la motocicleta sin seguro obligatorio.
            Cómo usamos los datos personales
            La aplicación móvil HELMY recopila y usa información para brindar servicios de alertas en caso de accidente, así como para ofrecer otros productos y servicios. La información, en general, recopilada por TA Edison se usa para realizar lo siguiente:	
            
            
            Mejorar la seguridad de los usuarios y de los servicios
            Brindar soporte al cliente
            Realizar tareas de investigación y de desarrollo
            Permitir la comunicación entre usuarios
            Enviar comunicaciones de marketing y de otro tipo a los usuarios
            Abordar temas relacionados con procedimientos legales
            TA Edison no vende ni divulga datos personales del usuario a terceros con fines de marketing directo, salvo que los usuarios den su consentimiento
            B.	TA Edison usa la información recopilada con los fines siguientes:
            1. Brindar servicios y funciones. TA Edison usa los datos recopilados para proporcionar, personalizar, mantener y mejorar nuestros productos y servicios.
            Esto incluye usarlos para lo siguiente:
            Crear y actualizar las cuentas de los usuarios.
            Activar las funciones que permiten a los usuarios compartir información con otras personas, por ejemplo, la ubicación donde los dispositivos HELMY detectaron un accidente de motocicleta.
            Realizar operaciones internas necesarias para brindar nuestros servicios, lo que incluye solucionar errores de software y problemas operacionales, realizar análisis, pruebas e investigación, y hacer un seguimiento y análisis de las tendencias de uso y actividades.
            2. Seguridad. Usamos datos personales para mantener la seguridad y la integridad de nuestros servicios y usuarios. Esto incluye lo siguiente:
            Usar los datos de los dispositivos de los Conductores para identificar comportamientos de conducción poco segura, como exceder la velocidad, o frenar y acelerar bruscamente, e informarles sobre prácticas más seguras. También usamos información de los dispositivos de conductores para verificar el tipo de vehículo que usaron para movilizarse.
            Usar los datos del dispositivo, ubicación, perfil y uso, entre otros, para prevenir, detectar y combatir el fraude o las actividades poco seguras como, por ejemplo, el robo o uso sin permiso de una motocicleta.
            4. Investigación y desarrollo. Podemos usar los datos que recopilamos para realizar pruebas, investigaciones, análisis, desarrollo de productos y aprendizaje automático con el fin de mejorar la experiencia del usuario. Esto nos ayuda a mejorar la seguridad de nuestros servicios, así como la prevención de su uso con fines ilegales o indebidos, desarrollar nuevas funciones y productos, y facilitar propuestas de seguros y de finanzas relativas a nuestros servicios.
            5. Permitir las comunicaciones entre usuarios. Por ejemplo, un Conductor puede enviar un SMS a un usuario para solicitar asistencia.
            6. Marketing. TA Edison puede usar los datos recopilados para comercializar nuestros servicios a los usuarios. Esto incluye enviar comunicaciones a los usuarios sobre los servicios, funciones, promociones, sorteos, estudios, encuestas, noticias, actualizaciones y eventos.
            Podemos usar los datos que recopilamos para personalizar las comunicaciones de marketing que enviamos (incluidos los anuncios), incluso según la ubicación, preferencias y configuraciones del usuario, por ejemplo, usamos la marca o referencia de la motocicleta o casco para enviar publicidad de los productos que se adecuan a esas marcas o referencias.
            7. Procedimientos y requisitos legales. Podemos usar los datos personales que recopilamos para investigar o resolver reclamos o disputas relacionados con el uso de los servicios o servicios que TA Edison proporciona, o según lo permita la ley vigente, o si lo solicitan organismos reguladores, entidades gubernamentales e investigaciones oficiales.
            8. Toma de decisiones automatizada
            Usamos datos personales para tomar decisiones automatizadas en relación con el uso de nuestros servicios. Esto incluye lo siguiente:
            Desactivación de las cuentas de aquellos usuarios involucrados en casos de fraude o en actividades que, de alguna manera, podrían dañar los servicios de TA Edison, sus usuarios y terceros. Por ejemplo, en algunos casos, se puede desactivar automáticamente a un usuario si se determina que está alterando datos para acceder sin permiso a una motocicleta.
            
            C.	Cookies y tecnologías de terceros
            TA Edison y otras tecnologías de identificación en la aplicación móvil HELMY, sitios web, correos electrónicos y anuncios en línea para los fines descritos en este aviso.
            Las cookies son pequeños archivos de texto que los sitios web, medios en línea y anuncios almacenan en el navegador o en el dispositivo. TA Edison usa cookies y tecnologías similares para los fines que se enumeran a continuación:
            Autenticar usuarios
            Recordar las preferencias y configuraciones del usuario
            Brindar y medir la efectividad de las campañas de publicidad
            Analizar el tránsito y las tendencias del sitio para comprender los comportamientos en línea y los intereses de las personas que interactúan con nuestros servicios
            También podemos permitir que terceros realicen mediciones de audiencia y servicios analíticos para nosotros, presenten anuncios en representación nuestra a través de internet, y realicen un seguimiento y nos informen sobre el rendimiento de estos anuncios. Estas entidades pueden usar cookies, balizas web, SDK y otras tecnologías para identificar los dispositivos que usan las personas cuando visitan nuestro sitio, así como cuando ingresan a otros sitios y servicios en línea.
            D.	Intercambio y divulgación de datos
            Algunos de los productos, servicios y funciones de TA Edison requieren que intercambiemos datos con otros usuarios o a pedido de estos. También podemos compartir información con nuestros afiliados, subsidiarias y Socios por motivos legales, o relacionados con reclamos o con disputas.
            TA Edison puede compartir los datos que recopilamos de la siguiente manera:
            1. A pedido del usuario
            Esto incluye compartir datos con las siguientes partes:
            Otras personas a pedido del usuario o por autorización previa del usuario. Por ejemplo, La ubicación exacta a un tercero en caso de un accidente.
            2. Con el público en general
            Las preguntas o los comentarios de los usuarios que se envían a través de foros públicos, como los blogs y las redes sociales de TA Edison, pueden estar al alcance de todos, por ejemplo, los datos personales incluidas en las preguntas o los comentarios enviados por un usuario.
            3. Con subsidiarias, afiliados, y aliados de TA Edison
            Compartimos información con las subsidiarias, afiliados y aliados que nos ayudan a proporcionar servicios, distribuir productos o a realizar tareas de procesamiento de datos en nuestro nombre. 
            4. Con proveedores de servicios y socios comerciales de TA Edison
            TA Edison proporciona datos a los proveedores, consultores, socios de marketing, empresas de investigación de mercado y otros proveedores de servicios o socios comerciales. Entre estos se incluyen los siguientes:
            Procesadores y facilitadores de pago
            Proveedores de almacenamiento en la nube
            Socios de marketing y proveedores de la plataforma de marketing, incluidos los servicios de publicidad en las redes sociales
            Proveedores de análisis de datos
            Socios de investigación, incluidos aquellos que realizan encuestas o proyectos de investigación 
            Proveedores que asisten a TA Edison para mejorar la seguridad y la protección de los usuarios de nuestros productos.
            Consultores, abogados, contadores y otros proveedores de servicios profesionales
            Proveedores de Vehicle Solutions y proveedores terceros de vehículos 
            Los datos podrán ser transferidos a cualquier servidor o base de datos de TA Edison o contratado por TA Edison (ejemplo, almacenamiento en la nube) en otro país, con fines de cumplir y suplir los procesos tecnológicos de los productos y servicios de TA Edison.
            5. Por motivos legales o ante un conflicto
            TA Edison puede compartir los datos personales de los usuarios si así lo exige la ley, reglamentación, licencia o acuerdo de operación, proceso legal o solicitud gubernamental vigentes, o cuando la divulgación es apropiada debido a asuntos de seguridad o similares. Esto incluye compartir datos personales con la fuerza del orden público, agentes de salud pública, otras entidades gubernamentales u otros terceros según sea necesario para hacer cumplir nuestros Términos del servicio, acuerdos del usuario u otras políticas, proteger los derechos o la propiedad de TA Edison, o los derechos, seguridad o propiedad de los demás, o en caso de un reclamo o una disputa relacionados con el uso de nuestros servicios. 
            Esto también incluye compartir datos personales con terceros en caso de cualquier fusión con otra compañía (o durante las negociaciones), venta de activos empresariales, consolidación o reestructuración, financiamiento, o compra de todo nuestro negocio o una parte de él a cargo de otra empresa.
            6. Con consentimiento
            TA Edison puede compartir los datos personales de un usuario de manera diferente a la descrita en este aviso si se lo notificamos, y este acepta el intercambio de información. Dicho cambio será documentado y la respuesta del usuario será almacenada. 
            E.	Mantenimiento y eliminación de los datos
            TA Edison conserva el perfil, transacciones y otros datos personales del usuario durante el tiempo que este mantiene su cuenta TA Edison.
            TA Edison puede conservar ciertos datos del usuario después de recibir una solicitud para eliminar una cuenta si es necesario, por ejemplo, para cumplir con los requisitos legales.
            Los usuarios o los clientes pueden solicitar la eliminación de su cuenta en cualquier momento a través del menú Configuración de privacidad en las cuentas creadas por el usuario para el uso de los productos y servicios de TA Edison. Después de recibir la solicitud, TA Edison elimina los datos que no está obligada a conservar conforme a requisitos legales, regulatorios, de impuestos, de seguros, de litigios u otros. Por ejemplo, TA Edison conserva los datos sobre dispositivo y uso a los fines descritos por un mínimo de 7 años y, mientras los retiene, también puede usarlos por motivos de seguridad, prevención y denuncia de fraudes, e investigación y desarrollo. En ciertas circunstancias es posible que TA Edison no pueda eliminar la cuenta de un usuario, por ejemplo, si tiene créditos, reclamos o disputas pendientes. Una vez que se resuelva el inconveniente que impedía la eliminación, TA Edison borrará la cuenta conforme a lo descrito anteriormente.
            TA Edison también puede conservar cierta información si es necesario para fines de seguridad y para prevenir el fraude. Por ejemplo, si se desactiva la cuenta de un usuario debido a una conducta peligrosa o a incidentes de seguridad, TA Edison puede conservar cierta información para prevenir que esta persona abra una nueva cuenta TA Edison en el futuro.
            
            F.	Bases para el procesamiento
            Solo recopilamos y usamos datos personales cuando tenemos las bases legales para hacerlo. Estos incluyen el procesamiento de información personal del usuario para brindar los servicios y las funciones solicitados, con relación a los intereses legítimos de TA Edison o de otras partes, para cumplir con nuestras obligaciones legales, o en función del consentimiento.
            Recopilamos y usamos datos personales solo cuando tenemos una o más bases legales para hacerlo, que pueden variar según la ubicación de nuestros usuarios, pero generalmente incluyen el procesamiento de datos personales para realizar lo siguiente:
            a. Proporcionar los servicios y las funciones solicitados
            Para proporcionar nuestros servicios, debemos recopilar y usar ciertos datos personales. Esto incluye lo siguiente:
            Datos del perfil de usuario para establecer y mantener su cuenta, verificar su identidad o el ID asignado a la placa de su motocicleta.
            b. Satisfacer los intereses legítimos de TA Edison o de otras partes
            Esto incluye el uso de datos personales para mantener y para mejorar la seguridad de nuestros usuarios. Específicamente, para evitar que los usuarios que tuvieron comportamientos inapropiados o peligrosos usen nuestros servicios, por ejemplo, mediante la retención de datos sobre los usuarios bloqueados para impedir que usen las cuentas asociadas con los productos y servicios de TA Edison. 
            Esto también incluye motivos tales como combatir el fraude, mejorar nuestros servicios, realizar actividades de marketing directo, investigación y desarrollo, y hacer cumplir los Términos del servicio de TA Edison.
            También abarca el uso de datos personales en la medida necesaria para satisfacer los intereses de otras personas o del público en general, como con relación a reclamos legales o de seguros, y para proteger los derechos y la seguridad de los demás.
            c. Cumplir con las obligaciones legales de TA Edison
            Por ejemplo, TA Edison está sujeto a leyes y a reglamentaciones en muchas ciudades y países, que le exigen recopilar y mantener datos sobre nuestros usuarios, y proporcionar copias de dichos datos al gobierno o a otras autoridades. Recopilamos y usamos información personal para cumplir con dichas leyes.
            TA Edison también puede compartir datos con la fuerza del orden público en casos de delitos o de amenazas a la seguridad pública, o por solicitudes de terceros relacionadas con procesos legales. 
            d. Con consentimiento
            TA Edison puede reunir y usar datos personales conforme al consentimiento que otorgó el usuario. Por ejemplo, podemos recopilar información personal a través de encuestas voluntarias. Sus respuestas se recabarán según su consentimiento y se eliminarán cuando ya no sean necesarias a los fines para los que se obtuvieron.
            Si un usuario da su consentimiento para que se recopile o se use su información personal, puede revocarlo en cualquier momento. Sin embargo, no podrá emplear ningún servicio o función que requiera reunir o usar estos datos.
            IV. Opciones y transparencia
            TA Edison también permite a los usuarios solicitar acceso o copias de sus datos, cambios, actualizaciones o eliminación de sus cuentas, o que TA Edison restrinja el procesamiento de su información personal.
            A. Configuración de privacidad
            El menú de configuración en las aplicaciones móviles y web de TA Edison brinda a los usuarios la capacidad de establecer o de actualizar las preferencias para compartir la ubicación y para recibir notificaciones móviles de TA Edison. 
            Datos de ubicación
            TA Edison usa los Servicios de ubicación de los dispositivos de sus usuarios para que les resulte más fácil pedir asistencia en caso de accidente detectado por los productos HELMY. 
            Los usuarios pueden permitir o impedir que TA Edison recopile datos de ubicación de sus dispositivos móviles a través del menú Configuración de privacidad en las aplicaciones móviles y web de TA Edison. Los usuarios y los clientes pueden activar o desactivar dichas recopilaciones a través de la configuración las aplicaciones.
            
            Datos compartidos con el servicio de emergencias (usuarios)
            Los usuarios que permitieron a TA Edison recopilar datos de ubicación de su dispositivo móvil también pueden activar la función de intercambio de datos de emergencia que comparte detalles con servicios de ambulancia y autoridades de tránsito. Estos detalles incluyen la ubicación aproximada en el momento en que se envió el SMS de emergencia, marca, modelo, color y matrícula de la motocicleta, nombre y número de teléfono del usuario, punto de partida y destino.
            Los usuarios pueden activar o desactivar esta función a través del menú Configuración de privacidad o del Centro de seguridad en la aplicación móvil HELMY de TA Edison.
            A.	 Permisos del dispositivo
            La mayoría de las plataformas de dispositivos móviles (iOS, Android, etc.) definieron ciertos tipos de datos de los dispositivos a los que las aplicaciones móviles no pueden acceder sin autorización del propietario, y estas plataformas tienen diferentes métodos para obtenerla. En los dispositivos con Android, se les notificará qué permisos necesita la HELMY App de TA Edison antes de que la usen por primera vez, y el uso de la HELMY App constituirá dicho consentimiento.
            Además, según su ubicación, los usuarios pueden tener derecho a presentar un reclamo relacionado con el manejo de sus datos personales por parte de TA Edison ante la autoridad de protección de datos de su país. Por ejemplo, los usuarios de la Unión Europea y de Sudamérica pueden enviar dichas solicitudes a las autoridades de protección de datos del país en el que viven.
            B. Solicitud de datos del usuario
            Acceso a datos: Los usuarios pueden solicitar una explicación acerca de por qué recopilamos sus datos y cómo los usamos.
            Recepción de datos: Los usuarios pueden solicitar una copia de los datos que TA Edison recopila de ellos con su consentimiento o según sea necesario para brindar nuestros servicios.
            Cambio o actualización de datos: Los usuarios pueden editar el nombre, número de teléfono, dirección de correo electrónico, método de pago y datos de su o sus motocicletas a través del menú Configuración en las aplicaciones móviles y web cada uno de los productos y servicios de TA Edison. También pueden solicitar que TA Edison cambie o actualice su información, incluso si consideran que no es exacta o que está incompleta.
            Eliminación de datos: Los usuarios pueden solicitar la eliminación de su cuenta en cualquier momento a través del menú Configuración de privacidad en las aplicaciones móviles y web de cada uno de los productos y servicios de TA Edison.
            Objeciones, restricciones y reclamos: Los usuarios pueden solicitar que dejemos de usar todos o algunos de sus datos personales, o que limitemos dicho uso. TA Edison puede continuar procesando datos después de dicha objeción o solicitud en la medida en que la ley lo requiera o lo permita.
            
            B.	Vigencia
            
            La presente Política entra en vigencia a partir del día 1 de diciembre de 2020.
            Los Datos Personales que sean almacenados, utilizados o transmitidos permanecerán en las bases de datos de TA Edison durante el tiempo que sea necesario para cumplir con las finalidades expuestas en este manual o para que la Empresa pueda cumplir con sus deberes legales.
            Sin embargo, la información será revisada cada año para verificar la veracidad del dato y finalidad de seguir con su tratamiento. De ser necesario TA Edison se reserva el derecho a modificar la presente Política de forma unilateral; sin perjuicio de esto, en caso de generarse algún cambio sustancial sobre la Política, se comunicará a los Titulares.
        </p>
        </div>
    </div>
</body>
</html>